version: "3.7"

services:
  recomend_server:
    build: ./build
    container_name: recommend-grpc-server
    volumes: 
      - .:/app
    ports:
      - "8080:8080"
    tty: true
  bigtable:
    image: "google/cloud-sdk:430.0.0"
    command: gcloud beta emulators bigtable start --host-port 0.0.0.0:8086
    ports:
      - 8086:8086